### ISSUE TITLE
No module named 'properties' error

### ISSUE THREAD

**Issue by afxlab** [Dene33/blender_jarvis#1]
File "C:\Users\Administrator\Desktop\blender-3.3.0-windows-x64\3.3\scripts\addons\blender_jarvis-main\ui.py", line 2, in <module>
    from properties import MDMToBlenderProperties
ModuleNotFoundError: No module named 'properties'

**Comment by Dene33** [comment]
@afxlab Should be some problem with Blender 3, I'll check how to fix it. Meanwhile, you can try it with Blender 2.93. Thanks

**Comment by Dene33** [comment]
That was not a Blender version-related bug. Now should be fixed, and release (0.2) is updated. Thanks for reporting.

**Comment by afxlab** [comment]
oh wow, I thought it supported 3.3, so sorry!
Thank you for the fix.
